import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { roboto_cons } from "@/fonts/roboto";
// import { cn } from "clsx-tailwind-merge";
import Topbar from "@/app/components/topbar";
import Toplinks from "./components/Navbar";
import Header from "./components/Header";
import PageTitle from "./components/PageTitle";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto_cons.className}>
        <Topbar />
        <main className="max-w-screen-xl mx-auto">
          <Toplinks />
          <Header />
          <PageTitle />
          {children}
        </main>
          <Footer />
      </body>
    </html>
  );
}
